# Generated by Django 5.2.4 on 2025-07-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_movies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
